### ISSUE TITLE
dcat_fields.md - Distribution doesn't have an identifier

### ISSUE THREAD

**Issue by chris-sepa** [datagovuk/guidance#6]
A DCAT distribution has to have an identifier (URI).

**Comment by davidread** [comment]
Thanks - good spot.

I've now added it to the spec. It's not mandatory for data.json, but clearly specifying it helps CKAN, and it is the norm for DCAT.

**Comment by chris-sepa** [comment]
Wow! That was quick.

Thanks,

Chris Sweeney
SEPA
